// Theme
export { ThemeProvider, useTheme } from "./components/theme-provider"
export type { Theme, ThemeProviderProps, ThemeProviderState } from "./components/theme-provider"
export { applyCompanyTheme } from "./lib/company-theme"
export type { CompanyTheme, CompanyThemeTokens } from "./lib/company-theme"
export { useCompanySubdomain, getSubdomain } from "./hooks/use-company-subdomain"
export type {
  UseCompanySubdomainOptions,
  UseCompanySubdomainResult,
} from "./hooks/use-company-subdomain"

// Components
export { ModeToggle } from "./components/mode-toggle"
export { EmptyState } from "./components/empty-state"
export { ConfirmDialog } from "./components/confirm-dialog"
export { PageHeader } from "./components/page-header"
export { StatusDot } from "./components/status-dot"
export { StatusBadge } from "./components/status-badge"
export type { StatusBadgeVariant } from "./components/status-badge"
export { ProgressBar } from "./components/progress-bar"
export { FormField } from "./components/form-field"
export { BaseDialog } from "./components/base-dialog"
export type { BaseDialogProps, BaseDialogSize } from "./components/base-dialog"
export { FormDialogLayout, FormDialog } from "./components/form-dialog"
export type { FormDialogProps, FormDialogSize } from "./components/form-dialog"
export { AuthCard } from "./components/auth-card"
export { Pagination } from "./components/pagination"
export type { PaginationProps } from "./components/pagination"
export { TableSkeleton } from "./components/table-skeleton"
export { SearchInput } from "./components/search-input"
export { PasswordInput } from "./components/password-input"
export { Combobox } from "./components/combobox"
export type { ComboboxOption, ComboboxProps } from "./components/combobox"
export { MultiCombobox } from "./components/multi-combobox"
export type { MultiComboboxProps } from "./components/multi-combobox"
export { ColorPicker } from "./components/color-picker"
export type { ColorPickerProps } from "./components/color-picker"
export { Rating } from "./components/rating"
export type { RatingProps } from "./components/rating"
export { DatePicker, DateTimePicker } from "./components/date-picker"
export type { DatePickerProps } from "./components/date-picker"
export { StatCard } from "./components/stat-card"
export { DataTableWrapper } from "./components/data-table-wrapper"
export { MobileCardList } from "./components/mobile-card-list"
export { ResponsiveDataView } from "./components/responsive-data-view"
export { Toaster } from "./components/toaster"

// App shell
export { AppShell } from "./components/app-shell"
export type { AppShellProps } from "./components/app-shell"
export { SidebarNav } from "./components/sidebar-nav"
export type { NavItem, SidebarNavProps } from "./components/sidebar-nav"
export { UserMenu } from "./components/user-menu"
export type { AppUser, UserMenuItem, UserMenuProps } from "./components/user-menu"
export { RowActionsMenu } from "./components/row-actions-menu"
export type { RowAction, RowActionsMenuProps } from "./components/row-actions-menu"
export { defaultRenderLink } from "./components/types"
export type { RenderLink, RenderLinkProps } from "./components/types"

// Utilities
export { cn } from "./lib/utils"
export { extractApiError } from "./lib/api-error"

// Hooks
export { useDisclosure } from "./hooks/use-disclosure"
export { useIsDesktop } from "./hooks/use-is-desktop"
export { useCustomToast, toast } from "./hooks/use-toast"
